[[themes]]
name = "tokyonight"
[themes.palette]
background = "#1a1b26"
foreground = "#a9b1d6"
black = "#32344a"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#85b1f7"
magenta = "#bb9af7"
cyan = "#0db9d7"
white = "#c0caf6"
bright_black = "#444b6a"
bright_red = "#ff4499"
bright_green = "#73daca"
#bright_yellow = "#"
#bright_blue = "#"
bright_magenta = "#ff007c"
#bright_cyan = "#"
bright_white = "#fdf6e3"

[themes.component_style]
block_title = { fg = "Magenta" }
border = { fg = "White" }
