# Hyprland init
exec-once = waybar &
exec-once = hyprpaper 
exec-once = mako &
exec-once = hyprlauncher -d &
exec-once = fish -c spotify_notify & 

# core 
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP #some fix, idk

# gtk settings
exec = gsettings set org.gnome.desktop.interface gtk-theme "Tokyonight-Dark"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
exec = gsettings set org.gnome.desktop.interface cursor-theme "Future-cyan-cursors"

# Clipboard
#exec-once = wl-paste --type text --watch cliphist store
#exec-once = wl-paste --type image --watch cliphist store

