### WINDOWS AND WORKSPACES ###

## WORKSPACES ##

workspace = special:magic, on-created-empty:footclient
workspace = w[tv1]s[false], gapsout:0, gapsin:0
workspace = f[1]s[false], gapsout:0, gapsin:0
windowrule = border_size 0, match:float 0, match:workspace w[tv1]s[false]
windowrule = rounding 0, match:float 0, match:workspace w[tv1]s[false]
windowrule = border_size 0, match:float 0, match:workspace f[1]s[false]
windowrule = rounding 0, match:float 0, match:workspace f[1]s[false]

## WINDOWS ##

windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# bottles
windowrule {
    name = bottles-winx
    match:class = ^(com.usebottles.bottles)$

    float = on
    size = 1000 600
}

# spotify
windowrule {
    name = spotify
    match:class = ^(spotify)$

    float = on
    size = 1000 900
}

# video player
windowrule {
  name = video-player
    match:class = ^(org.gnome.Showtime)$

    float = on
    size = 600 400
}

# proton mail
windowrule {
    name = proton-mail-electron
    match:class = ^(Proton Mail)$

    float = on
    size = 1000 900
}


# proton pass
windowrule {
    name = proton-pass-electron
    match:class = ^(Proton Pass)$

    float = on
    size = 1000 700
}
