## defines
$browser = zen-browser
$terminal = footclient ## don't forget to enable foot-server.socket
$fileManager = footclient yazi 
$menu = hyprlauncher 
$reload_waybar = pkill waybar; waybar &

## source modules
source = modules/env.conf
source = modules/execs.conf
source = modules/monitors.conf
source = modules/generals.conf
source = modules/rules.conf
source = modules/keybinds.conf
source = modules/animations.conf

