# ~/.config/hypr/hyprlauncher.conf

general {
    grab_focus = true
}

ui {
    window_size = 400 400
}

cache {
    enabled = true
}

finders {
    default_finder = desktop
    desktop_icons = false

    # Prefixes to trigger different search modules
    unicode_prefix = .
    math_prefix = =
    font_prefix = %
}
